### ISSUE TITLE
.

### ISSUE THREAD

**Issue by ghost** [Yummygum/city-lights-icons-vsc#32]

**Comment by noudadrichem** [comment]
This issue should be fixed and published already. Are you using the latest version?

**Comment by MindInSky** [comment]
I reinstalled the theme and when asked to select if colours or the default option for icons, I selected colours and I got the same error, here's message I get, I'm on VSCodium on Mac, in case that helps.

Edit to add: using v1.1.5 which is published on VSCodium extensions

PS: Used wrong account before, sorry about that, and thanks a lot for answering.

![image](https://user-images.githubusercontent.com/10949530/98016983-426a7280-1dc4-11eb-9772-b4b35549b6f5.png)

**Comment by MindInSky** [comment]
Update:

I was able to get past this by installing the extension manually

- make sure to have `vsce` else `npm install -g vsce`
- git clone the repo
- at repo root directory:
  `yarn install`
  `vsce package` 
  `code --install-extension city-lights-icon-vsc-1.1.5.vsix`

Maybe it needs to be republished to VsCode with the fix ? I'm not sure, but I can confirm the fix is there.

Edit: 
- https://open-vsx.org/extension/yummygum/city-lights-icon-vsc#review-details the version is 1.1.5, however it was published 2 months ago, which means the fix is not there, as it was added on #31 
- https://marketplace.visualstudio.com/items?itemName=Yummygum.city-lights-icon-vsc is ver 1.1.3, the fix is also not there.

Credit where credit is due : https://stackoverflow.com/questions/50714638/install-extension-from-a-specific-repo-branch-on-github
